"""Builds the Kaiju skin's wordmark: Oxanium ExtraBold set as outlines, leaned into a charge.

Writes src/shared/ui/kaiju-wordmark.ts (the outline, as one SVG path) and wordmark-preview.png.
Needs fonttools, skia-pathops, uharfbuzz and pillow.
"""
import io
import math
import os

import pathops
import uharfbuzz as hb
from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont
from fontTools.varLib import instancer
from PIL import Image, ImageChops, ImageDraw

HERE = os.path.dirname(os.path.abspath(__file__))
SOURCE = os.path.join(HERE, 'oxanium.ttf')
OUTPUT = os.path.join(HERE, '..', '..', 'src', 'shared', 'ui', 'kaiju-wordmark.ts')
PREVIEW = os.path.join(HERE, 'wordmark-preview.png')

TEXT = 'TASK STUDIO'
WEIGHT = 800
# Output units: the capitals are this tall; the extrusion and glow get PAD on every side.
CAP = 24.0
PAD = 3.0
# How far the letters lean forward, in degrees, and the extra space between them, in font units.
LEAN = 9
TRACK = 26

# The dorsal plate's outline, as fractions of its box: a swept spike with concave sides. The same
# one `PLATE` draws in `src/shared/ui/kaiju-icons.tsx`.
PLATE = [(0.56, 0), (0.63, 0.3), (0.76, 0.62), (1, 1), (0, 1), (0.22, 0.64), (0.4, 0.3)]
# Which letters wear a crest, and the plates on it: where along the bar (0-1) and how tall, in
# font units. The widest bar is the T's.
CREST_LETTERS = {'T'}
CREST = [(0.2, 150), (0.5, 230), (0.8, 150)]
# How far a plate's root sinks into the letter, so the union has no seam.
SINK = 30


def load() -> TTFont:
    font = TTFont(SOURCE)
    return instancer.instantiateVariableFont(font, {'wght': WEIGHT})


def shape(font: TTFont, text: str):
    buffer = io.BytesIO()
    font.save(buffer)
    face = hb.Face(buffer.getvalue())
    hb_font = hb.Font(face)
    run = hb.Buffer()
    run.add_str(text)
    run.guess_segment_properties()
    hb.shape(hb_font, run, {'kern': True, 'liga': False})
    return run.glyph_infos, run.glyph_positions


def crowned(glyph_set, name: str, cap_height: int):
    """The glyph with its crest of plates fused on: a fresh outline drawn through `pen`."""
    letter = pathops.Path()
    glyph_set[name].draw(letter.getPen(glyphSet=glyph_set))

    bounds = BoundsPen(glyph_set)
    glyph_set[name].draw(bounds)
    left, _, right, _ = bounds.bounds

    plates = pathops.Path()
    pen = plates.getPen()
    for along, height in CREST:
        width = height * 0.64
        centre = left + (right - left) * along
        root = cap_height - SINK
        for index, (fx, fy) in enumerate(PLATE):
            point = (centre + (fx - 0.5) * width, root + (1 - fy) * (height + SINK))
            (pen.moveTo if index == 0 else pen.lineTo)(point)
        pen.closePath()

    return pathops.op(letter, plates, pathops.PathOp.UNION)


def build():
    font = load()
    order = font.getGlyphOrder()
    glyphs = font.getGlyphSet()
    cap_height = font['OS/2'].sCapHeight
    scale = CAP / cap_height
    lean = math.tan(math.radians(LEAN))

    infos, positions = shape(font, TEXT)

    # Two passes over the same layout: bounds first, so the path can be placed at the origin.
    def place(pen_for):
        cursor = 0
        for info, position in zip(infos, positions):
            name = order[info.codepoint]
            if name != 'space':
                pen = pen_for(cursor + position.x_offset)
                if name in CREST_LETTERS:
                    crowned(glyphs, name, cap_height).draw(pen)
                else:
                    glyphs[name].draw(pen)
            cursor += position.x_advance + TRACK
        return cursor - TRACK

    def transform(offset):
        # x' = s*x + s*lean*y + dx, y' = -s*y + dy: font y runs up, SVG y runs down.
        return (scale, 0, scale * lean, -scale, offset * scale, 0)

    bounds = BoundsPen(None)
    advance = place(lambda offset: TransformPen(bounds, transform(offset)))
    min_x, min_y, max_x, max_y = bounds.bounds

    shift_x, shift_y = PAD - min_x, PAD - min_y
    svg = SVGPathPen(None, ntos=lambda value: f'{value:.2f}'.rstrip('0').rstrip('.'))
    place(
        lambda offset: TransformPen(
            svg,
            (scale, 0, scale * lean, -scale, offset * scale + shift_x, shift_y),
        )
    )

    width = round(max_x - min_x + 2 * PAD, 2)
    height = round(max_y - min_y + 2 * PAD, 2)
    return svg.getCommands(), width, height, advance


def write(path: str, width: float, height: float):
    source = f"""// Generated by `custom-font/kaiju/build-wordmark.py`: Oxanium ExtraBold outlines, leaned forward.
// Edit the script and re-run it rather than this file.
export const KAIJU_WORDMARK = {{
  width: {width},
  height: {height},
  path: '{path}',
}} as const;
"""
    with open(OUTPUT, 'w', encoding='utf-8', newline='\n') as handle:
        handle.write(source)


def preview(path: str, width: float, height: float):
    """A rough raster of the outline, for checking by eye: lilac face over a deep-violet extrusion."""
    from fontTools.svgLib.path import parse_path
    from fontTools.pens.recordingPen import RecordingPen

    scale = 10
    image = Image.new('RGB', (int(width * scale) + 40, int(height * scale) + 40), (9, 6, 16))
    draw = ImageDraw.Draw(image)

    recording = RecordingPen()
    parse_path(path, recording)

    contours, current = [], []
    for operator, args in recording.value:
        if operator == 'moveTo':
            current = [args[0]]
        elif operator == 'lineTo':
            current.append(args[0])
        elif operator == 'qCurveTo':
            # One control point and the end: sample the quadratic.
            (cx, cy), (ex, ey) = args
            sx, sy = current[-1]
            for step in range(1, 9):
                t = step / 8
                current.append(
                    (
                        (1 - t) ** 2 * sx + 2 * (1 - t) * t * cx + t * t * ex,
                        (1 - t) ** 2 * sy + 2 * (1 - t) * t * cy + t * t * ey,
                    )
                )
        elif operator in ('closePath', 'endPath'):
            if current:
                contours.append(current)
            current = []
    # Even-odd by XOR-ing each contour into a mask, so counters stay open.
    for dx, dy, colour in ((0.9, 1.1, (84, 40, 170)), (0, 0, (236, 222, 255))):
        mask = Image.new('L', image.size, 0)
        for contour in contours:
            layer = Image.new('L', image.size, 0)
            ImageDraw.Draw(layer).polygon(
                [(20 + (x + dx) * scale, 20 + (y + dy) * scale) for x, y in contour], fill=255
            )
            mask = ImageChops.difference(mask, layer)
        image.paste(colour, (0, 0), mask)
    image.save(PREVIEW)


if __name__ == '__main__':
    commands, width, height, advance = build()
    write(commands, width, height)
    try:
        preview(commands, width, height)
    except Exception as error:  # noqa: BLE001
        print('preview skipped:', error)
    print(f'wordmark {width} x {height}, {len(commands)} chars of path')
